name: node-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Prevents overlapping runs on the same branch
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install & Run Checks (conditional)
        shell: bash
        run: |
          if [ -f package.json ]; then
            echo "package.json found. Installing and running checks..."
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi

            # These only run if scripts exist; otherwise they no-op
            npm run -s lint --if-present
            npm run -s typecheck --if-present
            npm run -s build --if-present
          else
            echo "No package.json yet. Skipping Node checks."
          fi
